server:
  port: 8084

spring:
  application:
    name: microservicio-pagos
  
  # Configuración de Base de Datos H2 propia para Pagos
  datasource:
    url: jdbc:h2:mem:perfulandia_pagos_db
    driverClassName: org.h2.Driver
    username: sa
    password: 

  # Consola H2 para revisar las tablas de forma independiente
  h2:
    console:
      enabled: true
      path: /h2-console

  # Mostrar las sentencias SQL y crear tablas
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true

  sql:
    init:
      mode: never

# Registro en el Servidor Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/